// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSpansData = "spans_data"

// SpansData mapped from table <spans_data>
type SpansData struct {
	SpanID             string            `gorm:"column:span_id;type:String;primaryKey" json:"span_id"`
	TraceID            string            `gorm:"column:trace_id;type:String;primaryKey" json:"trace_id"`
	ParentSpanID       string            `gorm:"column:parent_span_id;type:String;not null" json:"parent_span_id"`
	Name               string            `gorm:"column:name;type:String;not null" json:"name"`
	Kind               int8              `gorm:"column:kind;type:Int8;not null" json:"kind"`
	StatusCode         int64             `gorm:"column:status_code;type:Int64;not null" json:"status_code"`
	StatusMsg          string            `gorm:"column:status_msg;type:String;not null" json:"status_msg"`
	ResourceAttributes map[string]string `gorm:"column:resource_attributes;type:Map(String, String);not null" json:"resource_attributes"`
	StartTimeMs        uint64            `gorm:"column:start_time_ms;type:UInt64;not null" json:"start_time_ms"`
	EndTimeMs          uint64            `gorm:"column:end_time_ms;type:UInt64;not null" json:"end_time_ms"`
	LogID              string            `gorm:"column:log_id;type:String;not null" json:"log_id"`
	AttrKeys           []string          `gorm:"column:attr_keys;type:Array(LowCardinality(String));not null" json:"attr_keys"`
	AttrValues         []string          `gorm:"column:attr_values;type:Array(String);not null" json:"attr_values"`
}

// TableName SpansData's table name
func (*SpansData) TableName() string {
	return TableNameSpansData
}
