// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSpansIndex = "spans_index"

// SpansIndex mapped from table <spans_index>
type SpansIndex struct {
	SpanID       string `gorm:"column:span_id;type:String;not null" json:"span_id"`
	TraceID      string `gorm:"column:trace_id;type:String;not null" json:"trace_id"`
	ParentSpanID string `gorm:"column:parent_span_id;type:String;not null" json:"parent_span_id"`
	Name         string `gorm:"column:name;type:String;not null" json:"name"`
	Kind         int8   `gorm:"column:kind;type:Int8;not null" json:"kind"`
	StatusCode   int64  `gorm:"column:status_code;type:Int64;not null" json:"status_code"`
	StatusMsg    string `gorm:"column:status_msg;type:String;not null" json:"status_msg"`
	LogID        string `gorm:"column:log_id;type:String;not null" json:"log_id"`
	SpaceID      int64  `gorm:"column:space_id;type:Int64;primaryKey" json:"space_id"`
	Type         int32  `gorm:"column:type;type:Int32;not null" json:"type"`
	UserID       int64  `gorm:"column:user_id;type:Int64;not null" json:"user_id"`
	EntityID     int64  `gorm:"column:entity_id;type:Int64;primaryKey" json:"entity_id"`
	Env          string `gorm:"column:env;type:String;not null" json:"env"`
	Version      string `gorm:"column:version;type:String;not null" json:"version"`
	Input        string `gorm:"column:input;type:String;not null" json:"input"`
	StartTimeMs  uint64 `gorm:"column:start_time_ms;type:UInt64;primaryKey" json:"start_time_ms"`
}

// TableName SpansIndex's table name
func (*SpansIndex) TableName() string {
	return TableNameSpansIndex
}
